# Generated by Django 5.0.14 on 2026-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='review_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='proposalactivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalactivitylog',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
