# Generated by Django 5.0.14 on 2026-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_backfill_review_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='review_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
