# Generated by Django 5.0.14 on 2026-08-26 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_proposal_review_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid UAE (+971XXXXXXXXX) or Pakistan (+92XXXXXXXXXX) phone number.', regex='^(\\+971\\d{9}|\\+92\\d{10})$')]),
        ),
    ]
